version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=document-processing-bucket
    depends_on:
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./db:/app/db
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker.dev
    environment:
      - REDIS_URL=redis://redis:6379
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=document-processing-bucket
    depends_on:
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./db:/app/db
    command: watchmedo auto-restart --directory=/app/src --pattern="*.py" --recursive -- celery -A src.worker.celery_app worker --loglevel=info